### ISSUE TITLE
Mirrorlist generator: "AttributeError: 'str' object has no attribute 'is_absolute'"

### ISSUE THREAD

**Issue by dr460nf1r3** [arcan1s/ahriman#106]
## Summary

When adding the `path` to the `mirrorlist_generator` values, Ahriman fails to start with `AttributeError: 'str' object has no attribute 'is_absolute'`

### Steps to reproduce

1. Activate mirrorlist trigger
2. Supply a configuration containing the `path` setting
3. See Ahriman failing to start up

### Expected behavior

Ahriman starts up. 

### Logs

~~~
[ERROR 2023-08-13 14:36:01,678] [stderr]: process exception
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/ahriman/application/handlers/handler.py", line 100, in call
cls.run(args, architecture, configuration, report=args.report)
File "/usr/lib/python3.11/site-packages/ahriman/application/handlers/validate.py", line 55, in run
if validator.validate(configuration.dump()):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1040, in validate
self.__validate_definitions(definitions, field)
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1110, in __validate_definitions
result = validate_rule(rule)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1085, in validate_rule
return validator(definitions.get(rule, None), field, value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1491, in _validate_schema
self.__validate_schema_mapping(field, schema, value)
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1504, in __validate_schema_mapping
if not validator(value, update=self.update, normalize=False):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1040, in validate
self.__validate_definitions(definitions, field)
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1110, in __validate_definitions
result = validate_rule(rule)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/cerberus/validator.py", line 1085, in validate_rule
return validator(definitions.get(rule, None), field, value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/ahriman/core/configuration/validator.py", line 160, in _validate_path_is_absolute
if constraint and not value.is_absolute():
^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_absolute'
~~~
~~~
[ahriman@61fd61d7dd25 /]$ ahriman version
Module version 2.10.2
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
~~~
~~~
[mirrorlist]
target = mirrorlist_generator

[mirrorlist_generator]
description = Chaotic-AUR mirrorlist
homepage = https://aur.chaotic.cx
package = chaotic-mirrorlist
servers = https://geo-mirror.chaotic.cx/$repo/$arch
path = /etc/pacman.d/chaotic-mirrorlist
~~~

**Comment by arcan1s** [comment]
fixed in d9eaf17a113d60568f45278eaa0ef1e39d6c8463.

The issue appears during configuration validator, because it has been configured to check if path is absolute (later it will be converted to relative to root). However, the extractor used always returns absolute path, so technically this check is redundant
