### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#84]
## Summary

ahriman depends on `python-aioauth-client`

### Steps to reproduce

Install ahriman on pure manjaro and run web service

### Logs

```
× ahriman-web@x86_64.service - ArcH linux ReposItory MANager web server (x86_64 architecture)
     Loaded: loaded (/usr/lib/systemd/system/ahriman-web@.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Wed 2023-01-25 08:16:01 JST; 2min 44s ago
   Duration: 531ms
    Process: 47284 ExecStart=/usr/bin/ahriman --architecture x86_64 web (code=exited, status=1/FAILURE)
   Main PID: 47284 (code=exited, status=1/FAILURE)
        CPU: 527ms

Jan 25 08:16:01 Hayao-Server ahriman[47284]:   File "/usr/lib/python3.10/site-packages/ahriman/web/web.py", line 28, in <module>
Jan 25 08:16:01 Hayao-Server ahriman[47284]:     from ahriman.core.auth import Auth
Jan 25 08:16:01 Hayao-Server ahriman[47284]:   File "/usr/lib/python3.10/site-packages/ahriman/core/auth/__init__.py", line 23, in <module>
Jan 25 08:16:01 Hayao-Server ahriman[47284]:     from ahriman.core.auth.oauth import OAuth
Jan 25 08:16:01 Hayao-Server ahriman[47284]:   File "/usr/lib/python3.10/site-packages/ahriman/core/auth/oauth.py", line 20, in <module>
Jan 25 08:16:01 Hayao-Server ahriman[47284]:     import aioauth_client
Jan 25 08:16:01 Hayao-Server ahriman[47284]: ModuleNotFoundError: No module named 'aioauth_client'
Jan 25 08:16:01 Hayao-Server python[47284]: [ERROR] [stderr]: process exception
                                            Traceback (most recent call last):
                                              File "/usr/lib/python3.10/site-packages/ahriman/application/handlers/handler.py", line 102, in call
                                                cls.run(args, architecture, configuration, report=args.report, unsafe=args.unsafe)
                                              File "/usr/lib/python3.10/site-packages/ahriman/application/handlers/web.py", line 51, in run
                                                from ahriman.web.web import run_server, setup_service
                                              File "/usr/lib/python3.10/site-packages/ahriman/web/web.py", line 28, in <module>
                                                from ahriman.core.auth import Auth
                                              File "/usr/lib/python3.10/site-packages/ahriman/core/auth/__init__.py", line 23, in <module>
                                                from ahriman.core.auth.oauth import OAuth
                                              File "/usr/lib/python3.10/site-packages/ahriman/core/auth/oauth.py", line 20, in <module>
                                                import aioauth_client
                                            ModuleNotFoundError: No module named 'aioauth_client'
Jan 25 08:16:01 Hayao-Server systemd[1]: ahriman-web@x86_64.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 08:16:01 Hayao-Server systemd[1]: ahriman-web@x86_64.service: Failed with result 'exit-code'.
```

**Comment by arcan1s** [comment]
oof, fixed with 2.6.1. Unfortunately currently there are checks for minimal and full installation only and cases with partial setup are not covered :(
